---
title: "Expectation maximization"
author: "[Michael Love](http://mikelove.github.io)"
output: html_document
---

Here I recreate a figure from Ramesh Sridharan's excellent 
[lecture notes](https://people.csail.mit.edu/rameshvs/content/gmm-em.pdf)
on the EM algorithm for the Guassian mixture model.

```{r echo=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

```{r echo=FALSE, fig.width=7, fig.height=7}
x <- rnorm(2e6, 3, 1)
x <- x[x > .01]
h1 <- hist(x, breaks=seq(from=.01,to=10,length=100), plot=FALSE)
h2 <- hist(log(x), breaks=seq(from=log(.01),to=log(10),length=100), plot=FALSE)
plot(function(x) log(x), xlim=c(0, 5), ylim=c(0,log(5)),
     main="Jensen's Inequality with log and E")
lines(h1$mids, h1$density, col="coral3", lwd=3)
lines(h2$density, h2$mids, col="dodgerblue", lwd=3)
s <- 2:5
segments(s,rep(0,length(s)),s,log(s),lty=2)
segments(rep(0,length(s)),log(s),s,log(s),lty=2)
arrows(3, .2, 3, 0, col="coral3", lwd=2, length=.1)
arrows(.5, mean(log(x)), 0, mean(log(x)), col="dodgerblue", lwd=2, length=.1)
```

$$ \textrm{max}_\theta \textrm{E}_{Z|X,\theta^t} \left[ \log L(\theta; X, Z) \right] $$

$$ = \textrm{E}_{Z|X,\theta^t} \left[ \log \prod_i \prod_c \pi_c f(x_i; \mu_c)^{\mathbb{1}(z_i = c)} \right] $$

$$ = \textrm{E}_{Z|X,\theta^t} \left[ \sum_i \sum_c \mathbb{1}(z_i = c) (\log \pi_c + \log f(x_i; \mu_c)) \right] $$

$$ \sum_i \sum_c \textrm{E}_{Z|X,\theta^t} \mathbb{1}(z_i = c) \left( \log \pi_c + \log \frac{1}{2\pi} - \frac{1}{2} (x_i - \mu_c)^2 \right) $$ 

Now differentiate this double sum with respect to the mean of one of the components, say $\mu_1$, and set equal to zero:

$$ \sum_i \textrm{E}_{Z|X,\theta^t} \mathbb{1}(z_i = 1) (x_i - \mu_1) = 0 $$

Define $\textrm{E}_{Z|X,\theta^t} \mathbb{1}(z_i = 1) \equiv w_i$,
which we can calculate using our probability model, $X$, and
$\theta^t$. Then we have:

$$ \sum_i w_i (x_i - \mu_1) = 0 $$

$$ \hat{\mu}^{t+1}_1 = \frac{\sum_i w_i x_i}{\sum_i w_i} $$

```{r}
n <- 4000
true.mus <- c(0, 5)
true.sigma2 <- c(1, 2)
x <- c(rnorm(n/2, true.mus[1], sqrt(true.sigma2[1])),
       rnorm(n/2, true.mus[2], sqrt(true.sigma2[2])))
hist(x, breaks=50, col="grey")
```

```{r}
alpha <- c(.5, .5)
mus <- c(1, 2)
sigma2 <- c(1, 1)
```

```{r messages=FALSE}
niter <- 10
library(rafalib)
nullplot(true.mus[1]-5,true.mus[2]+5,0,niter+1,ylab="iterations",xlab="estimates of mu, sigma2")
abline(v=true.mus,lty=2)
points(true.mus, rep(0,2), pch=1:2, col="blue")
arrows(true.mus - sqrt(true.sigma2), rep(0,2),
       true.mus + sqrt(true.sigma2), rep(0,2),
       length=.1, code=3, col="blue")
points(mus, rep(1,2), pch=1:2)
arrows(mus - sqrt(sigma2), rep(1,2),
       mus + sqrt(sigma2), rep(1,2),
       length=.1, code=3)
for (i in 1:niter) {
  w <- cbind(alpha[1] * dnorm(x, mus[1], sqrt(sigma2[1])),
             alpha[2] * dnorm(x, mus[2], sqrt(sigma2[2])))
  w <- w / rowSums(w)
  N <- colSums(w)
  alpha <- N / n
  mus <- 1/N * c(sum(w[,1] * x), sum(w[,2] * x))
  sigma2 <- 1/N * c(sum(w[,1] * (x - mus[1])^2),
                    sum(w[,2] * (x - mus[2])^2))
  points(mus, rep(i+1,2), pch=1:2)
  arrows(mus - sqrt(sigma2), rep(i+1,2),
         mus + sqrt(sigma2), rep(i+1,2),
         length=.1, code=3)
}
```

<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1345710/>

```{r messages=FALSE}
library(BSgenome.Hsapiens.UCSC.hg38)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
g <- genes(TxDb.Hsapiens.UCSC.hg38.knownGene)
promoters <- flank(g, width=1500, both=TRUE)
seq <- getSeq(Hsapiens, promoters)
```

```{r}
gc <- as.vector( letterFrequency(seq, letters="GC") / 3000 )
cpg <- as.vector( vcountPDict(PDict("CG"), seq) / 3000 )
norm.cpg <- cpg / (gc/2)^2
```

```{r}
hist(norm.cpg, breaks=50, col="grey")
```

