---
title: "Homework 1"
author: "your name here"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: html_document
---

# Question 1

Make a ggplot showing the number of pseudogenes over the organism
`type` (doesn't matter if you include or exclude "Wheat", because 
plants are missing data for the pseudogene count).

Sort the `orgs` table to show just the rows for the three organisms 
with the most pseudogenes.

# Question 2

Make a nice looking table using `kable`, which shows the ratio of
transcripts (`tx`) to the number of genes (just add `coding` and
`noncoding` genes), averaged for each organism `type`.

Which type of organism has the fewest number of transcripts to genes?

Which type of organism has the most transcripts to genes?

# Question 3

Load the brain RNA data up until the PCA plot. So `logcts` should be
a matrix with log10 counts of dimension $48948 \times 1409$.

Plot the expression of the gene `ENSG00000090539.15` over the 
`condition`, the sub-tissues of the brain. (Note if you are using
a base R plot, suggest `las=2` for the labels and modifying the
`mar` parameter for plot margins to make space for labels.)

For what two values of `condition` is the mean log counts the highest for 
this gene?

This gene is called CHRD, and one can find 
information about individual genes on websites such as Ensembl, Wikipedia,
GeneCards, or GTEx. Look over these pages. Briefly (one sentence), 
what role does CHRD have in development?

* http://ensembl.org/Homo_sapiens/Gene/Ontologies/biological_process?db=core;g=ENSG00000090539;r=3:184380073-184390736
* https://www.genecards.org/cgi-bin/carddisp.pl?gene=CHRD
* https://en.wikipedia.org/wiki/Chordin
* https://www.gtexportal.org/home/gene/CHRD

According to GTEx, in what tissue or sub-tissue is expression of CHRD the highest?

# Question 4

We will use the PCA performed in the lecture notes, i.e. the `pc` object.

Use `identify` to find the sample number of the outlying cortex sample 
in the bottom of the PCA plot.

Use a scatterplot to compare the log counts of this sample to another cortex sample,
looking only at the top 500 genes by variance (e.g. the genes specified in `o`).

For comparison, also make a scatterplot of two other non-outlier cortex samples 
against each other.

For the scatterplots, draw a y=x line in red to more easily recognize differences
across the samples.

Roughly speaking, what do you see in the scatterplot that may be different 
about the outlying cortex sample?
